version: "3"
services:
 bepusdt:
    container_name: usdt-pay
    image: ghcr.io/lufeiit/usdt-pay:latest
    restart: always
    ports:
      - "6080:6080"
    environment:
      EXPIRE_TIME: 3600 # 订单有效期，单位秒
      USDT_RATE: '~0.98' # USDT汇率，默认留空则获取Okx交易所的汇率(每分钟同步一次)，支持多种写法，如：7.4 表示固定7.4、～1.02表示最新汇率上浮2%、～0.97表示最新汇率下浮3%、+0.3表示最新加0.3、-0.2表示最新减0.2，以此类推；如参数错误则使用固定值7.4
      APP_URI: 'https://xxx' # 应用访问地址，留空则系统自动获取，前端收银台会用到，建议设置
      AUTH_TOKEN: xxxxxxxxx # 认证Token，对接发卡网/支付平台会用到这个参数进行回调
      # LISTEN: ':6080' # 服务器HTTP监听地址
      REWRITE_HTTPS: true # 重写http成https，使用反向代理的时候往往需要强制https模式
      WALLET_ADDRESS: [TRON]:xxxxx,[POLY]:xxxxx # 收款钱包地址，多个请用半角符逗号,分开；当然，同样也支持通过机器人添加。单条格式为: [TRON|POLY|OP|BSC]:地址, 其中[]部分为支付链标识
      # TRADE_IS_CONFIRMED # TRON网络是否需要确认，禁用可以提高回调速度，启用则可以防止交易失败，默认0
      # ETH_CONFIRMATION # ETH兼容网络需要网络确认的块数，影响Polygon、Optimism，Bep20
      TG_BOT_TOKEN: 1111:1111 # Telegram Bot Token 必须设置
      TG_BOT_ADMIN_ID: 1111  # Telegram Bot 管理员ID 必须设置
      # TG_BOT_GROUP_ID: #Telegram 群组ID，设置之后机器人会将交易消息会推送到此群
      TRON_SERVER_API: TRON_GRID # 可选TRON_SCAN，TRON_GRID，推荐TRON_GRID和TRON_GRID_API_KEY搭配使用，更准更强更及时
      TRON_GRID_API_KEY: xxxxxx # TRON_GRID API KEY，如果使用TRON_GRID，必须设置
      POLYGON_SCAN_API_KEY: xxxxxx # Polygon Scan API KEY，如果使用Polygon，必须设置
      OPTIMISM_EXPLORER_API_KEY: xxxxxx # Optimism Explorer API KEY，如果使用Optimism，必须设置
      BSC_SCAN_API_KEY: xxxxxx # BSC Scan API KEY，如果使用BSC，必须设置
      PAYMENT_AMOUNT_RANGE: 1,99999 # 支付监控的允许数额范围(闭区间)，设置合理数值可避免一些诱导式诈骗交易提醒
      # TRON_GRPC_NODE: 18.141.79.38:50051
